services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FRONTEND_ORIGIN=http://localhost:3000
      - DATABASE_URL=postgresql://app:app_password@postgres:5432/aquachain
    volumes:
      - ./views:/app/views:ro
      - ./public:/app/public:ro
    depends_on:
      - postgres
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=aquachain
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8.10
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=Admin123!
      - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=10
      - PGADMIN_CONFIG_LOGIN_BANNER=Authorized use only
    ports:
      - "5050:80"
    depends_on:
      - postgres
  hardhat:
    image: node:18
    working_dir: /app
    volumes:
      - ./Contracts:/app
    command: bash -lc "npm ci || npm install && npx hardhat node --hostname 0.0.0.0"
    ports:
      - "8545:8545"
volumes:
  pg_data:
